'use strict';

// One reviewed presentation source for Flutter and calendar output. No identity
// or membership is generated, and this script has no network/Firestore access.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const international = require('./data/internationalClubPresentation.json');
const japaneseCompetitions = ['football_j1', 'football_j2', 'football_j3', 'football_j_league_cup', 'football_emperor_cup'];
// GOAL detail + official club history/stadium evidence, documented in the
// closure packet. These broad labels are only usable in Japanese competitions.
const scopedAliases = {'FC Tokyo': ['Tokyo'], 'Tochigi SC': ['Tochigi']};

function outputs() {
  const entries = ['j1', 'j2', 'j3'].flatMap(division =>
    require(`./data/${division}Teams`)[`${division}Teams`].map(team => ({
      nameJa: team.nameJa,
      nameEn: team.nameEn,
      aliases: [...new Set([team.nameJa, team.nameEn, ...team.aliases,
        ...(team.id === 'jef_united_chiba' ? ['JEF United'] : [])])],
      scopedAliases: scopedAliases[team.nameEn] || [],
      competitionKeys: scopedAliases[team.nameEn] ? japaneseCompetitions : [],
      logoUrl: team.logoUrl,
      source: `functions/scripts/data/${division}Teams.js`,
    }))
  ).concat(international.map(team => ({
    nameJa: team.nameEn === 'Arsenal' ? 'アーセナル' : '',
    nameEn: team.nameEn,
    aliases: team.competitionKeys?.length ? [] : [...new Set([team.nameEn, ...team.aliases])],
    scopedAliases: team.competitionKeys?.length ? [...new Set([team.nameEn, ...team.aliases])] : [],
    competitionKeys: team.competitionKeys || [],
    logoUrl: team.logoUrl,
    source: team.source,
  })));
  const json = JSON.stringify(entries, null, 2) + '\n';
  const dartString = value => JSON.stringify(value).replace(/\$/g, '\\$');
  const dart = '// GENERATED by functions/scripts/generateTeamPresentation.js.\n' +
    '// Display metadata only: never use this catalog to assign a Team ID.\n' +
    'const clubPresentationEntries = <ClubPresentation>[\n' + entries.map(e =>
      `  ClubPresentation(${dartString(e.nameJa)}, ${dartString(e.nameEn)}, ${dartString(e.logoUrl)}, [${e.aliases.map(dartString).join(', ')}], [${e.competitionKeys.map(dartString).join(', ')}], [${e.scopedAliases.map(dartString).join(', ')}]),`
    ).join('\n') + '\n];\n\n' +
    'class ClubPresentation {\n' +
    '  const ClubPresentation(this.nameJa, this.nameEn, this.logoUrl, this.aliases, this.competitionKeys, this.scopedAliases);\n' +
    '  final String nameJa;\n  final String nameEn;\n  final String logoUrl;\n  final List<String> aliases;\n  final List<String> competitionKeys;\n  final List<String> scopedAliases;\n}\n';
  return new Map([
    ['functions/src/domain/teamPresentationCatalog.json', json],
    ['lib/domain/policies/club_presentation_data.dart', dart],
  ]);
}

function check() {
  for (const [file, content] of outputs()) {
    if (fs.readFileSync(path.join(root, file), 'utf8') !== content) {
      throw new Error(`Stale presentation catalog: ${file}`);
    }
  }
}

if (require.main === module) {
  if (process.argv.includes('--check')) check();
  else for (const [file, content] of outputs()) fs.writeFileSync(path.join(root, file), content);
}
module.exports = {check};
