/**
 * seedJ1Minimum.js
 *
 * Seeds the minimum Firestore data required for the J1 League / Kashima Antlers
 * end-to-end flow to work in the Flutter app.
 *
 * Documents written:
 *   leagues/j1_league        — set() (full overwrite)
 *   teams/kashima_antlers    — set() (full overwrite)
 *   translationMaps/football — set({ merge: true }) (safe merge, no data loss)
 *
 * Usage:
 *   cd /Users/User/sportsCalender/sports_calendar_sync/functions
 *   node scripts/seedJ1Minimum.js
 *
 * Prerequisites:
 *   - functions/serviceAccountKey.json must exist (never commit this file)
 *   - firebase-admin must be installed (npm install in functions/)
 */

'use strict';

const admin = require('firebase-admin');
const serviceAccount = require('../serviceAccountKey.json');
const { generateSearchKeywords } = require('./searchKeywords');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

async function seed() {
  // ── leagues/j1_league ──────────────────────────────────────────────────────
  await db.collection('leagues').doc('j1_league').set({
    nameEn: 'J1 League',
    nameJa: 'J1リーグ',
    country: 'Japan',

    // Phase 1 primary field
    competitionKey: 'football_j1',
    // Legacy alias — kept for syncFootball.ts and backward-compat queries
    sportKey: 'football_j1',
    // Legacy field — syncFootball.ts queries where('sportType', '==', 'football')
    sportType: 'football',

    dataSourceKey: 'apisports_football',

    // externalLeagueId is the Phase 1 canonical field
    externalLeagueId: 98,
    // rapidApiId is the legacy alias — syncFootball.ts reads this
    rapidApiId: 98,

    logoUrl: 'https://media.api-sports.io/football/leagues/98.png',
  });
  console.log('[seed] leagues/j1_league written');

  // ── teams/kashima_antlers ──────────────────────────────────────────────────
  // searchKeywords is generated by the shared generateSearchKeywords() utility.
  // Aliases cover mid-string matches (e.g. 'アントラーズ') and English variants.
  // The same function will be used by the future API-SPORTS import pipeline.
  const kashimaKeywords = generateSearchKeywords({
    nameJa: '鹿島アントラーズ',
    nameEn: 'Kashima',
    aliases: ['鹿島', 'アントラーズ', 'Kashima Antlers', 'Antlers'],
  });

  await db.collection('teams').doc('kashima_antlers').set({
    nameEn: 'Kashima',
    nameJa: '鹿島アントラーズ',
    leagueId: 'j1_league',
    country: 'Japan',

    // Phase 1 primary field
    competitionKey: 'football_j1',
    // Legacy alias
    sportKey: 'football_j1',
    // Legacy field — syncFootball.ts queries where('sportType', '==', 'football')
    sportType: 'football',

    dataSourceKey: 'apisports_football',

    // externalTeamId is the Phase 1 canonical field
    externalTeamId: 290,
    // rapidApiId is the legacy alias — syncFootball.ts reads this
    rapidApiId: 290,

    logoUrl: 'https://media.api-sports.io/football/teams/290.png',

    // Firestore array-contains search field.
    // Generated by generateSearchKeywords() — do not hard-code values here.
    searchKeywords: kashimaKeywords,
  });
  console.log('[seed] teams/kashima_antlers written');

  // ── translationMaps/football ───────────────────────────────────────────────
  // merge: true ensures existing keys in the document are not deleted.
  await db.collection('translationMaps').doc('football').set(
    {
      teams: {
        Kashima: '鹿島アントラーズ',
      },
      leagues: {
        'J1 League': 'J1リーグ',
      },
    },
    { merge: true },
  );
  console.log('[seed] translationMaps/football merged');

  console.log('[seed] Done — all documents written successfully.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('[seed] Error:', err);
  process.exit(1);
});
