/**
 * verifyJ1SampleGame.js
 *
 * Verifies minimal J1 sample game documents. Dry-run mode validates the
 * planned documents generated by seedJ1SampleGame.js without initializing
 * Firebase Admin SDK or reading/writing Firestore.
 *
 * Usage:
 *   node functions/scripts/verifyJ1SampleGame.js --dry-run
 *   node functions/scripts/verifyJ1SampleGame.js
 */

'use strict';

const { buildSampleGameDocs } = require('./seedJ1SampleGame');
const {
  CURRENT_J1_COMPETITION_SEASON_KEY,
} = require('./data/competitionSeasons');

const REQUIRED_FIELDS = [
  'leagueId',
  'competitionKey',
  'competitionSeasonKey',
  'sportKey',
  'homeTeamId',
  'homeTeamNameJa',
  'homeTeamNameEn',
  'homeTeamLogoUrl',
  'awayTeamId',
  'awayTeamNameJa',
  'awayTeamNameEn',
  'awayTeamLogoUrl',
  'startTimeUTC',
  'startTimeJST',
  'timezone',
  'status',
  'venue',
  'broadcastPlatforms',
  'externalFixtureId',
  'rapidApiFixtureId',
];

function parseArgs(argv) {
  return {
    dryRun: argv.includes('--dry-run'),
  };
}

function check(label, condition, detail) {
  const status = condition ? 'PASS' : 'FAIL';
  console.log(`  [${status}] ${label}${detail ? ': ' + detail : ''}`);
  return condition;
}

function checkEqual(label, actual, expected) {
  return check(
    label,
    actual === expected,
    `${JSON.stringify(actual)} (expected: ${JSON.stringify(expected)})`,
  );
}

function checkExists(label, exists) {
  return check(label, exists, exists ? 'document exists' : 'document MISSING');
}

function checkQueryContainsAll(label, docs, expectedIds) {
  const actualIds = docs.map((doc) => doc.id);
  const missing = expectedIds.filter((id) => !actualIds.includes(id));
  return check(
    label,
    missing.length === 0,
    missing.length === 0
      ? `all expected docs found (${actualIds.join(', ')})`
      : `missing ${JSON.stringify(missing)} (got ${JSON.stringify(actualIds)})`,
  );
}

function chunkArray(values, size) {
  const chunks = [];
  for (let i = 0; i < values.length; i += size) {
    chunks.push(values.slice(i, i + size));
  }
  return chunks;
}

function coveredTeamIds(docs) {
  const ids = new Set();
  for (const doc of docs) {
    ids.add(doc.data.homeTeamId);
    ids.add(doc.data.awayTeamId);
  }
  return Array.from(ids);
}

function startTimeDate(value) {
  if (value instanceof Date) return value;
  if (typeof value === 'string') return new Date(value);
  if (value && typeof value.toDate === 'function') return value.toDate();
  return null;
}

function validateTimeConsistency(startTimeUTCDate, startTimeJST) {
  const jstRegex = /^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})$/;
  const match = startTimeJST.match(jstRegex);
  if (!match) {
    return check('startTimeJST format', false, `"${startTimeJST}"`);
  }

  const [, yyyy, MM, dd, HH, mm] = match;
  const jstMs = Date.UTC(
    parseInt(yyyy, 10),
    parseInt(MM, 10) - 1,
    parseInt(dd, 10),
    parseInt(HH, 10),
    parseInt(mm, 10),
    0,
    0,
  );
  const utcFromJst = new Date(jstMs - 9 * 60 * 60 * 1000);
  const diffMs = Math.abs(utcFromJst.getTime() - startTimeUTCDate.getTime());

  return check(
    'startTimeUTC/JST consistency',
    diffMs < 60 * 1000,
    `UTC=${startTimeUTCDate.toISOString()}, JST=${startTimeJST}, diff=${diffMs}ms`,
  );
}

function validateDocShape(doc, now = new Date()) {
  let allPassed = true;
  const data = doc.data;

  console.log(`\nVerifying planned ${doc.path} ...`);
  for (const field of REQUIRED_FIELDS) {
    allPassed = check(
      `${doc.id}.${field} present`,
      data[field] !== undefined && data[field] !== null,
    ) && allPassed;
  }

  allPassed = checkEqual(`${doc.id}.leagueId`, data.leagueId, 'j1_league') && allPassed;
  allPassed = checkEqual(`${doc.id}.competitionKey`, data.competitionKey, 'football_j1') && allPassed;
  allPassed = checkEqual(`${doc.id}.competitionSeasonKey`, data.competitionSeasonKey, CURRENT_J1_COMPETITION_SEASON_KEY) && allPassed;
  allPassed = checkEqual(`${doc.id}.sportKey`, data.sportKey, 'football_j1') && allPassed;
  allPassed = checkEqual(`${doc.id}.timezone`, data.timezone, 'Asia/Tokyo') && allPassed;
  allPassed = checkEqual(`${doc.id}.status`, data.status, 'scheduled') && allPassed;
  allPassed = check(
    `${doc.id}.home/away teams differ`,
    data.homeTeamId !== data.awayTeamId,
    `${data.homeTeamId} vs ${data.awayTeamId}`,
  ) && allPassed;
  allPassed = check(
    `${doc.id}.broadcastPlatforms is array`,
    Array.isArray(data.broadcastPlatforms),
  ) && allPassed;

  const start = startTimeDate(data.startTimeUTC);
  allPassed = check(`${doc.id}.startTimeUTC parseable`, start instanceof Date && !Number.isNaN(start.getTime())) && allPassed;
  if (start) {
    allPassed = check(
      `${doc.id}.startTimeUTC is future`,
      start > now,
      `start=${start.toISOString()}, now=${now.toISOString()}`,
    ) && allPassed;
    allPassed = validateTimeConsistency(start, data.startTimeJST) && allPassed;
  }

  return allPassed;
}

function validatePlannedDocs(docs) {
  let allPassed = true;
  const ids = new Set();
  const coveredTeams = new Set();

  console.log(`[verify:j1:sample-games] planned games: ${docs.length}`);
  allPassed = check('planned game count >= 3', docs.length >= 3) && allPassed;
  allPassed = check('planned game count <= 5', docs.length <= 5) && allPassed;

  for (const doc of docs) {
    allPassed = check(`unique doc id ${doc.id}`, !ids.has(doc.id)) && allPassed;
    ids.add(doc.id);
    allPassed = validateDocShape(doc) && allPassed;
    coveredTeams.add(doc.data.homeTeamId);
    coveredTeams.add(doc.data.awayTeamId);
  }

  allPassed = check(
    'covered followed-team candidates >= 8',
    coveredTeams.size >= 8,
    Array.from(coveredTeams).join(', '),
  ) && allPassed;

  return allPassed;
}

async function fetchUpcomingGamesForFollowedTeams({ db, teamIds, nowTimestamp, limit = 50 }) {
  const docsById = new Map();

  for (const chunk of chunkArray(teamIds, 10)) {
    const homeSnap = await db.collection('games')
      .where('homeTeamId', 'in', chunk)
      .where('startTimeUTC', '>=', nowTimestamp)
      .orderBy('startTimeUTC')
      .limit(limit)
      .get();
    console.log(`  [INFO] homeTeamId in [${chunk.join(', ')}] returned ${homeSnap.docs.length} docs`);

    const awaySnap = await db.collection('games')
      .where('awayTeamId', 'in', chunk)
      .where('startTimeUTC', '>=', nowTimestamp)
      .orderBy('startTimeUTC')
      .limit(limit)
      .get();
    console.log(`  [INFO] awayTeamId in [${chunk.join(', ')}] returned ${awaySnap.docs.length} docs`);

    for (const doc of [...homeSnap.docs, ...awaySnap.docs]) {
      docsById.set(doc.id, doc);
    }
  }

  return Array.from(docsById.values())
    .sort((a, b) => startTimeDate(a.data().startTimeUTC) - startTimeDate(b.data().startTimeUTC))
    .slice(0, limit);
}

async function verifyMultiFollowQuery({ db, plannedDocs, nowTimestamp }) {
  const expectedIds = plannedDocs.map((doc) => doc.id);
  const teamIds = coveredTeamIds(plannedDocs);

  console.log('\n=== Section 2: Multi-follow home-screen query checks ===');
  console.log(`Followed team IDs: ${teamIds.join(', ')}`);
  console.log('Query shape mirrors GameRepository.fetchUpcomingGamesForTeams:');
  console.log('  homeTeamId in chunk OR awayTeamId in chunk, startTimeUTC >= now, orderBy startTimeUTC, limit 50');
  console.log('  status filter: none');

  const docs = await fetchUpcomingGamesForFollowedTeams({ db, teamIds, nowTimestamp });
  return checkQueryContainsAll(
    'merged followed-team query returns planned sample games',
    docs,
    expectedIds,
  );
}

async function verifyFirestore() {
  const admin = require('firebase-admin');
  const serviceAccount = require('../serviceAccountKey.json');

  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });

  try {
    const db = admin.firestore();
    const plannedDocs = buildSampleGameDocs();
    let allPassed = true;
    const nowTimestamp = admin.firestore.Timestamp.now();

    for (const planned of plannedDocs) {
      console.log(`\nVerifying Firestore ${planned.path} ...`);
      const doc = await db.collection('games').doc(planned.id).get();
      allPassed = checkExists(`${planned.path} exists`, doc.exists) && allPassed;
      if (!doc.exists) continue;

      const data = doc.data();
      allPassed = validateDocShape({ id: planned.id, path: planned.path, data }) && allPassed;

      const homeSnap = await db.collection('games')
        .where('homeTeamId', '==', data.homeTeamId)
        .where('startTimeUTC', '>=', nowTimestamp)
        .orderBy('startTimeUTC')
        .limit(50)
        .get();
      allPassed = check(
        `${planned.id} appears in homeTeamId upcoming query`,
        homeSnap.docs.some((candidate) => candidate.id === planned.id),
      ) && allPassed;

      const awaySnap = await db.collection('games')
        .where('awayTeamId', '==', data.awayTeamId)
        .where('startTimeUTC', '>=', nowTimestamp)
        .orderBy('startTimeUTC')
        .limit(50)
        .get();
      allPassed = check(
        `${planned.id} appears in awayTeamId upcoming query`,
        awaySnap.docs.some((candidate) => candidate.id === planned.id),
      ) && allPassed;
    }

    allPassed = await verifyMultiFollowQuery({
      db,
      plannedDocs,
      nowTimestamp,
    }) && allPassed;

    return allPassed;
  } finally {
    await admin.app().delete();
  }
}

async function verify({ dryRun }) {
  if (dryRun) {
    console.log('[verify:j1:sample-games] dryRun: true');
    console.log('[verify:j1:sample-games] Firestore will not be read or written.');
    return validatePlannedDocs(buildSampleGameDocs());
  }

  console.log('[verify:j1:sample-games] dryRun: false');
  return verifyFirestore();
}

async function main() {
  let exitCode = 0;
  try {
    const allPassed = await verify(parseArgs(process.argv.slice(2)));
    console.log('\n' + (allPassed ? '✅ All sample game checks PASSED.' : '❌ One or more sample game checks FAILED.'));
    exitCode = allPassed ? 0 : 1;
  } catch (err) {
    console.error('[verify:j1:sample-games] Error:', err);
    exitCode = 1;
  }
  process.exit(exitCode);
}

if (require.main === module) {
  main();
}
